# Use the official image as a parent image
FROM python:3.6.3

# Set the working directory in the container
WORKDIR /workspace

# Note: GitHub Codespaces automatically maps your project into /workspace.

# Install any dependencies (optional)
RUN pip install --upgrade pip
